framework:
    messenger:
        transports:
            async:
                dsn: 'doctrine://default?queue_name=async&auto_setup=false'
        routing:
            'App\Message\HandleAITurnMessage': async
